### ISSUE TITLE
Installed but not working on Chroma Studio

### ISSUE THREAD

**Issue by kohdarrenn** [ChromaControl/ChromaControl#50] opened 2021-03-23 13:31 UTC
Chroma Controller installed and enabled, however Chroma Studio on Synapse not applying the effects to ASUS MB. Have tried creating new effects but the effect doesnt apply to the Motherboard circle, but it works on my other Razer devices.

![image](https://user-images.githubusercontent.com/79243821/112154145-f1e29d00-8c1e-11eb-97d3-3426a0596d92.png)
![image](https://user-images.githubusercontent.com/79243821/112154193-fc9d3200-8c1e-11eb-9cb4-32664ef469f3.png)
![image](https://user-images.githubusercontent.com/79243821/112154233-0757c700-8c1f-11eb-81a3-66b42ff78e44.png)

Thank you!

**Comment by AndrewBabbitt97** [comment] 2021-03-23 14:01
Duplicate of #46

**Closed** 2021-03-23 14:01 UTC
