### ISSUE TITLE
Armoury Crate doesn't like to communicate with Chroma Control. Outputs black 24/7

### ISSUE THREAD

**Issue by Laqota** [ChromaControl/ChromaControl#234] opened 2023-03-01 05:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have looked at the existing issue reported. Yet, my "In-game lighting effects" is turned on. Is this being updated anymore?

The Chroma Control - ASUS on Razer Synapse Outputs black 24/7. I am using an Strix B550-F Motherboard and it outputs black 24/7. Thanks!

### Expected behavior

Supposed to update Razer Synapses mouse color with the colors on the motherboard.

### Steps to reproduce

Open up Chroma Control, Open up Razer Synapse 3, and open up the Armoury Crate V5.3.4.0 and be disappointed.

### Exceptions or error messages (if any)

none

### Version number

0.1.4

### Anything else?

Windows 11 10.0.25300 Build 25300

ROG Strix B550-F Gaming

Razer Synapse 3 3.8.209.20311

Armoury Crate 5.3.4.0

Aura Service (Lighting Service) 3.05.78

**Comment by AndrewBabbitt97** [comment] 2023-03-01 21:24
Your expected behavior doesn't look right, you expect your Razer mouse to be synced to your motherboard? Because it works the other way around.

Chroma Control is used to sync 3rd party devices to Synapse Effects. So you will use Synapse to control your motherboard LEDs by assigning it an effect in Chroma Studio (in Synapse)

**Comment by Laqota** [comment] 2023-03-02 19:21
Doesn't work both ways anyways. I might be doing something wrong.. It just outputs black 24/7 no matter what I do.

**Comment by Laqota** [comment] 2023-03-02 19:22
By it outputs black. It just makes the LED on my motherboard black.

**Comment by AndrewBabbitt97** [comment] 2023-03-04 01:05
Need a screenshot of your chroma studio UI.

**Comment by Laqota** [comment] 2023-03-04 03:05
I reinstalled Armoury and it seems to be working now. Sorry for the mishap. Probably had a poisoned install.

**Comment by AndrewBabbitt97** [comment] 2023-03-05 00:05
Glad to hear your problem is fixed. I'll close this issue as resolved.

**Closed by AndrewBabbitt97** 2023-03-05 00:05 UTC
