### ISSUE TITLE
Chroma Control (Asus) loses connection to Asus devices after PC wakes up from sleep mode

### ISSUE THREAD

**Issue by tihomirbz** [ChromaControl/ChromaControl#154] opened 2021-11-30 22:56 UTC
Synapse - Armory Crate sync works perfectly fine on startup, however if the computer goes to sleep, after waking up the Asus device lighting can no longer be controlled from Synapse (and is out of sync with everything else). Even if I manually go to Synapse -> Chroma Control (Asus) and try to change the effects, it doesn't work. Issue doesn't appear to be caused by Armory Crate as I can still go into that app and change the lighting, Synapse also works fine for the Razor devices.

Synapse version 3.6.1130.111217
Armory Crate version 4.2.12.0
Chroma Control version 0.1.3.0

**Comment by saqibmubarak** [comment] 2021-12-12 11:20
My Synapse - Armory Crate sync doesn't even work on startup
![image](https://user-images.githubusercontent.com/14963445/145710173-786c9ef4-bbac-438c-8f32-2ca5d3f718e9.png)
all the lightning is still controlled by RGB... Once I forced stopped  Armoury process (It worked) but it stopped working later with the same method after the restart...

**Comment by AndrewBabbitt97** [comment] 2023-01-13 00:04
Duplicate of #37

**Closed by AndrewBabbitt97** 2023-01-13 00:04 UTC
