### ISSUE TITLE
Windows asks for Permission by email from other users

### ISSUE THREAD

**Issue by ofirda** [ChromaControl/ChromaControl#212] opened 2023-01-14 20:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have installed only user and at times when my son logs in and then I re login I get a message that I need to ask Permission by mail to use the app
then you have to open close, play with it to get it back on track but at times you can't without restart
not sure how to overcome this behavior

**Comment by AndrewBabbitt97** [comment] 2023-01-14 22:08
Some form of parental controls, this is a windows issue not a Chroma Control issue. App won't be eligible for parental controls after the next update comes out. Either way.

Closing as the issue is with windows, not Chroma Control.

**Closed by AndrewBabbitt97** 2023-01-14 22:08 UTC

**Comment by ofirda** [comment] 2023-01-15 06:38
Thank Andrew
When is the next update planned?
