### ISSUE TITLE
Can not control ASUS TUF GeForce RTX 4090

### ISSUE THREAD

**Issue by jmartensson** [ChromaControl/ChromaControl#191] opened 2022-10-29 13:22 UTC
I have enabled ASUS and it shows up in Synapse but nothing happens when I try to change the colors.

ASUS ROG STRIX X670E-F GAMING WIFI
ASUS TUF GeForce RTX 4090 24GB Gaming

I can change colors for the GÅU in Armoury Crate

**Comment by vishalchaudhary** [comment] 2022-10-31 09:09
I can confirm the same behaviour with ASUS ROG STRIX 4090 and MSI MPG Z790 Carbon WIFI MB

**Comment by AndrewBabbitt97** [comment] 2022-11-02 19:24
Duplicate of #178

**Closed by AndrewBabbitt97** 2022-11-02 19:24 UTC
