### ISSUE TITLE
Could someone please help?

### ISSUE THREAD

**Issue by Sbm7** [ChromaControl/ChromaControl#76] opened 2021-04-22 05:02 UTC
So I already left my original complaint/question and it is the question before this one. Since it seems no one has an answer, would it be possible for me to get the old Auraconnect download files? It worked flawlessly for me but this new Chroma Control is not even recognized in Synapse. Any help to the original question or simply the old auraconnect download files would be greatly appreciated. @AndrewBabbitt97 Hopefully I can get a response this time.

Original issue:
I have been using auraconnect since last february for my pc. Today, I updated my razer synapse to the latest version and I noticed the aura connect was no longer in the studio or devices tab. I then found out that auraconnect was archived. Upon downloading the newer chroma control, it appears to not be running when I click launch. It is not visible in task manager or the devices tab under connect in razer synapse. Could someone please help me as I would like to regain the functionality I once had. Thanks.
![image](https://user-images.githubusercontent.com/82786711/115660319-73eae200-a301-11eb-9c65-c40b7bd1f896.png)

**Comment by AndrewBabbitt97** [comment] 2021-04-22 05:29
First: Please don't open multiple issues for the same thing. I usually come around to issues on weekends as its my one time I tend to have available to work on my free time projects.

I will not be distributing or supporting AuraConnect anymore, the source is nearly identical to that of ChromaControl besides bootup process to support multiple manufacturers as well as an MSIX installer instead of InnoSetup.

In order to help I need your logs from %localappdata%\Local\Packages\ChromaControl.Asus_846pf09jn2fpg\LocalCache\Local\ChromaControl\logs

Also need a list of your Aura devices + a screenshot of the Armory Crate -> Settings -> Update Center page

**Comment by Sbm7** [comment] 2021-04-22 05:34
> First: Please don't open multiple issues for the same thing. I usually come around to issues on weekends as its my one time I tend to have available to work on my free time projects.
> 
> I will not be distributing or supporting AuraConnect anymore, the source is nearly identical to that of ChromaControl besides bootup process to support multiple manufacturers as well as an MSIX installer instead of InnoSetup.
> 
> In order to help I need your logs from %localappdata%\Local\Packages\ChromaControl.Asus_846pf09jn2fpg\LocalCache\Local\ChromaControl\logs
> 
> Also need a list of your Aura devices + a screenshot of the Armory Crate -> Settings -> Update Center page

Alright sorry. How do I access logs? As for the second request, my devies are an ASUS ROG STRIX Z390E-Gaming Motherboard, an argb strip, g skill trident z rgb ram (2 sticks) and an ROG STRIX RTX 2070 super. Here is the update center page.
![image](https://user-images.githubusercontent.com/82786711/115661011-7437ad00-a302-11eb-9c17-ab575e729acc.png)

**Comment by AndrewBabbitt97** [comment] 2021-04-22 05:35
Logs are in the following windows directory:
```%localappdata%\Packages\ChromaControl.Asus_846pf09jn2fpg\LocalCache\Local\ChromaControl\logs```

**Comment by Sbm7** [comment] 2021-04-22 05:40
> %localappdata%\Packages\ChromaControl.Asus_846pf09jn2fpg\LocalCache\Local\ChromaControl\logs

[ASUS.log](https://github.com/ChromaControl/ChromaControl/files/6355752/ASUS.log) I think these are the logs.

**Comment by AndrewBabbitt97** [comment] 2021-04-22 05:42
Please do the same for the logs in ```C:\Program Files (x86)\Razer\ChromaBroadcast\logs```

**Comment by Sbm7** [comment] 2021-04-22 05:46
There are multiple files here, not sure if I did it right.

[FortniteClient-Win64-Shipping.exe.log](https://github.com/ChromaControl/ChromaControl/files/6355782/FortniteClient-Win64-Shipping.exe.log)
[FortniteClient-Win64-Shipping.log](https://github.com/ChromaControl/ChromaControl/files/6355783/FortniteClient-Win64-Shipping.log)
[R5Apex.log](https://github.com/ChromaControl/ChromaControl/files/6355784/R5Apex.log)
[Razer Synapse Service.log](https://github.com/ChromaControl/ChromaControl/files/6355785/Razer.Synapse.Service.log)
[RazerSynapseService.exe.log](https://github.com/ChromaControl/ChromaControl/files/6355786/RazerSynapseService.exe.log)
[RzSDKService.exe.log](https://github.com/ChromaControl/ChromaControl/files/6355787/RzSDKService.exe.log)
[RzSDKService.log](https://github.com/ChromaControl/ChromaControl/files/6355788/RzSDKService.log)
[wallpaper32.exe.log](https://github.com/ChromaControl/ChromaControl/files/6355789/wallpaper32.exe.log)
[wallpaper32.log](https://github.com/ChromaControl/ChromaControl/files/6355790/wallpaper32.log)
[CB_FortniteClient-Win64-Shipping.exe.log](https://github.com/ChromaControl/ChromaControl/files/6355791/CB_FortniteClient-Win64-Shipping.exe.log)
[CB_RazerSynapseService.exe.log](https://github.com/ChromaControl/ChromaControl/files/6355792/CB_RazerSynapseService.exe.log)
[CB_RzSDKService.exe.log](https://github.com/ChromaControl/ChromaControl/files/6355793/CB_RzSDKService.exe.log)
[ChromaVisualizer.log](https://github.com/ChromaControl/ChromaControl/files/6355794/ChromaVisualizer.log)

**Comment by Sbm7** [comment] 2021-04-22 05:51
> Please do the same for the logs in `C:\Program Files (x86)\Razer\ChromaBroadcast\logs`

There are multiple files here, not sure if I did it right.

[CB_RzSDKService.exe.log](https://github.com/ChromaControl/ChromaControl/files/6355823/CB_RzSDKService.exe.log)
[ChromaVisualizer.log](https://github.com/ChromaControl/ChromaControl/files/6355824/ChromaVisualizer.log)
[FortniteClient-Win64-Shipping.exe.log](https://github.com/ChromaControl/ChromaControl/files/6355825/FortniteClient-Win64-Shipping.exe.log)
[FortniteClient-Win64-Shipping.log](https://github.com/ChromaControl/ChromaControl/files/6355826/FortniteClient-Win64-Shipping.log)
[R5Apex.log](https://github.com/ChromaControl/ChromaControl/files/6355827/R5Apex.log)
[Razer Synapse Service.log](https://github.com/ChromaControl/ChromaControl/files/6355828/Razer.Synapse.Service.log)
[RazerSynapseService.exe.log](https://github.com/ChromaControl/ChromaControl/files/6355829/RazerSynapseService.exe.log)
[RzSDKService.exe.log](https://github.com/ChromaControl/ChromaControl/files/6355830/RzSDKService.exe.log)
[RzSDKService.log](https://github.com/ChromaControl/ChromaControl/files/6355831/RzSDKService.log)
[wallpaper32.exe.log](https://github.com/ChromaControl/ChromaControl/files/6355832/wallpaper32.exe.log)
[wallpaper32.log](https://github.com/ChromaControl/ChromaControl/files/6355833/wallpaper32.log)
[CB_FortniteClient-Win64-Shipping.exe.log](https://github.com/ChromaControl/ChromaControl/files/6355834/CB_FortniteClient-Win64-Shipping.exe.log)
[CB_RazerSynapseService.exe.log](https://github.com/ChromaControl/ChromaControl/files/6355835/CB_RazerSynapseService.exe.log)

**Comment by AndrewBabbitt97** [comment] 2021-04-22 06:10
Given that there isnt a ```CB_ChromaControl.Asus.exe.log``` file It looks like the issue is with Synapse.

Please completely uninstall all of Synapse, reboot, then reinstall it and try again.

**Comment by Sbm7** [comment] 2021-04-22 15:58
> Given that there isnt a `CB_ChromaControl.Asus.exe.log` file It looks like the issue is with Synapse.
> 
> Please completely uninstall all of Synapse, reboot, then reinstall it and try again.

This did not work. Any other suggestions?

**Comment by qandres12** [comment] 2021-04-23 16:50
> 
> 
> > Given that there isnt a `CB_ChromaControl.Asus.exe.log` file It looks like the issue is with Synapse.
> > Please completely uninstall all of Synapse, reboot, then reinstall it and try again.
> 
> This did not work. Any other suggestions?

I believe the problem is with the update for synapse itself. if you can find a downgrade for it, it will work until its properly fixed.

**Comment by AndrewBabbitt97** [comment] 2021-06-11 00:22
Please reverify issue with latest Synapse version, this issue was opened around the time a lot of bugs were found and getting fixed in Synapse.

**Comment by juancarrilloberdejo** [comment] 2021-06-15 19:45
buenas, podrias ayudarme con esto?
![2021-06-15](https://user-images.githubusercontent.com/85964284/122113833-39289600-cde8-11eb-8d2b-0a9115aa2153.png)

**Comment by AndrewBabbitt97** [comment] 2021-06-15 20:17
> buenas, podrias ayudarme con esto?
> ![2021-06-15](https://user-images.githubusercontent.com/85964284/122113833-39289600-cde8-11eb-8d2b-0a9115aa2153.png)
> 

English here please.

Need Logs like I asked people before %localappdata%\Packages\ChromaControl.Asus_846pf09jn2fpg\LocalCache\Local\ChromaControl\logs

**Comment by juancarrilloberdejo** [comment] 2021-06-15 20:25
[CB_hid.exe.log](https://github.com/ChromaControl/ChromaControl/files/6658460/CB_hid.exe.log)
[CB_RazerSynapseService.exe.log](https://github.com/ChromaControl/ChromaControl/files/6658461/CB_RazerSynapseService.exe.log)
[CB_RestoreDevice.exe.log](https://github.com/ChromaControl/ChromaControl/files/6658462/CB_RestoreDevice.exe.log)
[CB_TTRGBPlus.exe.log](https://github.com/ChromaControl/ChromaControl/files/6658463/CB_TTRGBPlus.exe.log)
[CB_ChromaControl.Asus.exe.log](https://github.com/ChromaControl/ChromaControl/files/6658464/CB_ChromaControl.Asus.exe.log)
[CB_ChromaControl.Corsair.exe.log](https://github.com/ChromaControl/ChromaControl/files/6658465/CB_ChromaControl.Corsair.exe.log)
[CB_ChromaVisualizer.exe.log](https://github.com/ChromaControl/ChromaControl/files/6658466/CB_ChromaVisualizer.exe.log)


estos son los archivos?

**Comment by AndrewBabbitt97** [comment] 2021-07-05 23:08
Need files from %localappdata%\Packages\ChromaControl.Asus_846pf09jn2fpg\LocalCache\Local\ChromaControl\logs those are not the right files

**Comment by AndrewBabbitt97** [comment] 2023-01-12 23:52
Issue should be resolved in later Synapse updates.

**Closed by AndrewBabbitt97** 2023-01-12 23:52 UTC
Labels: question
