### ISSUE TITLE
Windows 11 Pro Wont install

### ISSUE THREAD

**Issue by RealRabidWolf** [ChromaControl/ChromaControl#176] opened 2022-06-08 13:56 UTC
it gives me an untrusted error and wont install

**Comment by zypher00** [comment] 2022-06-16 17:13
I am having issues as well on windows 10, it indicates that the developer is untrusted.

**Comment by AndrewBabbitt97** [comment] 2022-06-17 06:59
Closing as this is a duplicate of #173

**Closed** 2022-06-17 06:59 UTC
