### ISSUE TITLE
Doesn't work after sleep.

### ISSUE THREAD

**Issue by gward2** [ChromaControl/ChromaControl#199] opened 2023-01-09 22:51 UTC
I'm using version 0.1.4, with Corsair enabled, and I have to toggle on and off the switch in order to get it to function after sleep.

**Comment by AndrewBabbitt97** [comment] 2023-01-12 23:39
May have a solution to this in the upcoming release.

**Comment by AndrewBabbitt97** [comment] 2023-01-13 00:15
Duplicate of #37

**Closed by AndrewBabbitt97** 2023-01-13 00:15 UTC
