### ISSUE TITLE
Lighting effects fail to sync upon waking computer

### ISSUE THREAD

**Issue by Kaldaka** [ChromaControl/ChromaControl#187] opened 2022-09-10 16:14 UTC
Preliminary build info: I am using a windows 10 desktop running the latest verson at this time (10.0.19044 Build 19044). I don't know if this matters, but I also have Wallpaper Engine from Steam set to automatically run on startup. I have 4 corsair LL120 fans connected to a lightning node pro, an EKWB FLT120 and EKWB Velocity CPU water cooling cover connected to a Razer ARGB controller, and an Asus Rog strix x370-F gaming mobo with RAM: part number F4-3200C16-8GTZR.

After turning on my computer from power off, the lighting effects sync fine (I have all my lights set to cycle through the rainbow gradually). If I let my computer go to sleep (where the lights turn off and fans stop spinning) and then wake it, the EKWB parts will resync (I notice a brief kind of stuttering like they are trying to decide on a color to start syncing like when I power on the computer, but then will be fine), however the mobo lighting will be frozen on its manufacturer-default rainbow cycle (but not cycling and not re-syncing). The RAM will sometimes resync, or it will remain frozen on the color that it was when the computer went to sleep. The fans used to resync, but after updating everything (windows, Chroma Control, Razer, iCue - sorry I can't isolate an update problem...) the fan LEDs will simply not turn back on.

Please let me know if I can provide more useful information. I would be more than happy to help make this product better.

Thank you very much!

**Comment by Hotpepere** [comment] 2022-10-11 06:42
Hello
I am neither a programmer nor a designer, but a user of chroma control (and formerly aura connect) for quite some time now.
and worries I had .... not with this software but especially with the synchronization with the other much better known.
first thing I notice is that your worries appear when you come out of standby and yes I can confirm that it happens, it's one of the few things that the software doesn't really like.
on the other hand when it happens you launch chroma control manually via your application shortcuts.
Turn off all your syncs.
switch debug on and then switch asus, msi, etc on on too
windows will open and all synchros will recover well
if that is the case
turn everything back to off and once done put the synchro switches back on only.

if everything does not work, it may come from the hardware in question such as the rams which do not like to be turned off and keep the cycles in memory if I may say so.
suddenly only one solution to reset
turn off the pc and disconnect the power supply from the pc for 30sec to 1 min
restart the pc it should work again

and if everything does not work unfortunately 2 possible causes
either a software update causes synchro problems with chroma control (often the case with razer synapse which causes concern for one update out of 2 with chroma connect because razer developers suck) and wait for a new update and hope let it be resolved

either the last update of one of the software causes a problem definitively and only a complete reinstallation of the software managing the rgb is necessary and in addition in a certain order because otherwise it can be problematic (example with armory crate from asus)
before reinstalling anything check whether or not there is an uninstaller dedicated to the brand like asus which allows you to remove all the small software lying around and which are related.
see video tutorials to note the order of installation and do not touch it anymore except razer which does automatic updates.
if despite its its not working last solution
complete windows reinstallation
a piece of advice, make a backup of your pc once everything is working on the rgb side.
as if you have the slightest problem restore it (backed up your personal data, passwords, favorites, etc. before).
well i hope it can help you

**Comment by AndrewBabbitt97** [comment] 2023-01-13 00:16
Duplicate of #37

**Closed by AndrewBabbitt97** 2023-01-13 00:16 UTC
