### ISSUE TITLE
Asus Tuf rtx 3090 wont sync with asus motherboard ram fans and razer peripherals

### ISSUE THREAD

**Issue by thedkmeir** [ChromaControl/ChromaControl#182] opened 2022-07-27 19:06 UTC
this is my full setup (only rgb stuff):

case: coolermaster cosomos c700p
cooler master rgb fans....
asus liquid cooled
hyperx rgb ram
razer keyboard 
razer mouse

this whole setups is working together perfactly in terms of rgb snc

buttttt
the new gpu i bought
asus tuf rtx 3090 wont sync with the rest....

any suggestions....

all the info i can provide:
yes the gpu shows up in asus armoury crate....
and yes it syncs to the rest of the hardware's rgb when used in asus armoury crate....

butttttt it wont sync to razer synapse like the rest does

all the hardware except the gpu can connect and sync with razer synapse....

**Comment by thedkmeir** [comment] 2022-07-27 19:10
tried reinstalling:
armoury crate
chroma control 
razer synapse

nothing helped....

**Comment by AndrewBabbitt97** [comment] 2022-07-27 22:50
Duplicate of #123 closing in favor of that.

**Closed** 2022-07-27 22:50 UTC
