### ISSUE TITLE
Chroma Control not working after screen goes to sleep

### ISSUE THREAD

**Issue by KushKrusader31** [ChromaControl/ChromaControl#256] opened 2023-05-11 00:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using Asus Aura Creator alongside Razer Chroma and Chroma Control. I have noticed lately that when my screen goes to sleep(not to be confused with the entire computer going to sleep, that is fully disabled), the RGB is no longer working for my entire PC. My Razer keyboard and mouse light back up, and continue operating as normal. I can(usually, not always) get it to work again if I open the Chroma Connect client, and toggle the Asus switch off and back on. When I do this however, it takes sometimes upwards of a few minutes before the PC lights start working again. Also, when this issue occurs, if I go straight into Aura Creator, I can switch from my "No lights" preset, to a different preset, and the lights will work through Asus. This is showing me that the Razer no longer has control, and it is being completely controlled by Asus at this point.

I would like to add, that I do believe this is a separate issue entirely from issue #37.

### Expected behavior

PC RGBs to automatically sync back up after waking screen back up from screensaver, along with the other connected Razer devices.

### Steps to reproduce

Enable Chroma Control, Chroma Connect.
Set create profile syncing Asus devices with other Razer devices.
Set sleep setting in PC to Never.
Set screen timeout to anything besides Never.
Let screen timeout.
Wake screen.
Asus devices no longer sync.

### Exceptions or error messages (if any)

No error message at all. Just stops syncronizing.

### Version number

Chroma Control version 1.4

### Anything else?

Windows 11 Pro 22H2, latest updates.
Armoury Crate version 5.6.3.0, latest updates
Aura Creator version 3.6.5, latest updates
Razer Synapse version 3.8.428.42117

My PC build:
Asus ROG Strix B550-F GAMING WIFI
Ryzen 9 5900x
G.Skill TridentZ RGB
Asus TUF RTX 3080 Ti
Asus ROG Strix 850w PSU
10x Antec aRGB 120mm case fans
Asus ROG Ryujin 240mm AIO

**Comment by AndrewBabbitt97** [comment] 2023-05-14 05:29
Duplicate of #37

**Closed by AndrewBabbitt97** 2023-05-14 05:29 UTC
