### ISSUE TITLE
Asus VGA not working

### ISSUE THREAD

**Issue by johnlin1225** [ChromaControl/ChromaControl#178] opened 2022-07-05 08:16 UTC
My mainboard and ram is working, but VGA is not, should I give you some logs to fix this problem?

**Comment by Kukulkahn** [comment] 2022-07-21 16:01
Same issue happening here. Graphics card is ASUS RTX3080, refuses to be controlled by ChromaControl.
DEBUG Log:

info: ChromaControl.Hosting.ModuleService[0]
      Initializing Chroma Control - Asus v0.1.3...
info: ChromaControl.Hosting.ModuleService[0]
      Initializing Device Provider...
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: ENE_RGB_For_ASUS0 - 8 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: ENE_RGB_For_ASUS1 - 8 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: Mainboard_Master - 4 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: AddressableStrip 1 - 120 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: AddressableStrip 2 - 120 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: AddressableStrip 3 - 120 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Initializing Razer Chroma Broadcast SDK...
info: ChromaControl.Hosting.ModuleService[0]
      Chroma Control - Asus Started Succesfully!
info: ChromaControl.Hosting.ModuleService[0]
      Razer Chroma Broadcast API Connected


Installed Armoury Crate Components:
Item                       Version     
----                       -------     
Armoury Crate UWP App      5.1.5.0     
ROG Live Service           1.4.10.0    
Aura Service (Lighting Service)  3.05.40     
Armoury Crate lite service  5.1.4       
Aura Wallpaper Service     No instalado
ASUS AIOFan HAL            1.1.47.0    
ASUS AURA Extension Card HAL  1.1.0.18    
ASUS AURA Motherboard HAL  1.3.4.0     
AacDisplay                 1.2.27      
AacVGA                     0.0.5.2     
KingstonDram               1.1.12      
AURA DRAM Component        1.1.18      
ENE RGB HAL                1.1.39.18

**Comment by Kukulkahn** [comment] 2022-07-25 17:43
After many days of hard debuggind, installing and reinstalling windows, etc.. 
I finally find the culprit.
Everything works fine with NVIDIA 512.95 drivers. 
If you install any version above this one, Chroma Control refuses to detect ASUS ROG Strix RTX3080 VGA leds.. (Everything else has been double checked, and I even installed all the drivers between this 512.95 version and the newest one to see where the breaking point was.

Hoping this gets fixed for future GPU driver update compatibilities.
THANKS!

**Comment by LoganCatanese** [comment] 2022-07-26 23:52
> After many days of hard debugging, installing and reinstalling windows, etc.. I finally found the culprit. Everything works fine with NVIDIA 512.95 drivers. If you install any version above this one, Chroma Control refuses to detect ASUS ROG Strix RTX3080 VGA leds.. (Everything else has been double checked, and I even installed all the drivers between this 512.95 version and the newest one to see where the breaking point was.
> 
> Hoping this gets fixed for future GPU driver update compatibilities. THANKS!

Yes, same issue here with ASUS ROG Strix 2070 Super. I as well hope this is updated!

**Comment by AndrewBabbitt97** [comment] 2022-07-27 22:49
With this being the case someone will have to report the issue to Asus and NVidia as there's nothing I can do on my side to fix it.

I want to try to work on a documentation site for the project over the weekend if I can find some time, I'll add this to it.

**Comment by Kukulkahn** [comment] 2022-07-28 15:45
Thanks Andrew! By you saying you can't do anything I then understand that what's working ok in 512.95 drivers but it's broken in later versions, is the connection between the asus aura game sdk and the gpu drivers? Is that correct? @AndrewBabbitt97

**Comment by AndrewBabbitt97** [comment] 2022-07-31 21:11
@Kukulkahn I cant confirm for sure, I have an NVidia Founders Edition 2080 Ti, so the card doesnt have RGB on it at all. All my RGB on my GPU comes through the water block in an RGB cable. It could have to do with device HALs on the ASUS side, but I cant say for sure at this moment.

**Comment by SCDoll12** [comment] 2022-08-15 16:02
@AndrewBabbitt97 @Kukulkahn I can confirm that rolling back the driver to 512.95 fixes the issue. Had been trying to find a solution for this work a few weeks. Armoury Crate fails to load most times for me on drivers higher than 512.95. I would have to guess this is a NVIDIA and ASUS problem unfortunately.

**Comment by Kukulkahn** [comment] 2022-08-15 21:01
I guess we should try posting this issue in the ASUS ROG forums, and see if any of the admins there can make this an official known issue and escalate it to ASUS and Nvidia.

**Comment by jusxon** [comment] 2022-09-01 01:39
Is there a post yet on the Asus ROG forums? I cannot find anything.

**Comment by AndrewBabbitt97** [comment] 2022-10-01 23:20
![HAL](https://user-images.githubusercontent.com/2308261/193431669-7b68d325-f66a-4574-8250-df2b978b6a17.png)

A new GPU HAL was released on Armory Crate yesterday. Seeing as I do not have an ASUS GPU, If anyone ends up updating to the latest HAL + Latest NVidia driver and confirm issues are fixed that would be great to know.

**Comment by JohnJobs0822** [comment] 2022-10-04 17:08
> ![哈尔](https://user-images.githubusercontent.com/2308261/193431669-7b68d325-f66a-4574-8250-df2b978b6a17.png)
> 
> 昨天在 Armory Crate 上发布了一个新的 GPU HAL。鉴于我没有华硕 GPU，如果有人最终更新到最新的 HAL + 最新的 NVidia 驱动程序并确认问题已得到解决，那将是很高兴知道的。

It's not help...So,Nvida XXXX U

**Comment by Hotpepere** [comment] 2022-10-12 06:43
Hello
first my setup:
win 11 fresh with just driver and free of any prior installations of asus, TT, razer, etc.
motherboard asrock X570 taichi razer edition
asus rog strix gtx1080ti sliX2
ThermalTake Toughram X2 memory
corsair headset VOID
everything else led management, mouse, ventilation, etc. 100% compatible with razer synapse without any worries

Here are the tests performed:
first test
fresh win 11
Install driver nvidia 517.48
installing armory crate 3.2.3.0
installing latest corsair ICUE
Install razer synapse3 latest version
install chroma control 0.14

graphics card and memory not detected in armory crate
chroma control well installed in synapse -chroma connect
after debug chroma control ram bar synchronized with synapse but not graphics card
Corsair Void headset always in sync too

after researching the latest armory crate no longer take into account the geforce series 10 for info so a priori normal

second test:
Install driver nvidia 517.48
installation armory crate full installation package 1.0.3.6 13/06/2022(1.77gbbytes offline installation)
installing latest corsair ICUE
Install razer synapse3 latest version
install chroma control 0.14

graphics card and memory detected in armory crate (seems to be the solution for series 10)
chroma control well installed in synapse -chroma connect
chroma control ram bar synchronized with synapse but not graphics card
Corsair Void headset always in sync too

third quiz:
Install driver nvidia 517.48
installation armory crate full installation package 1.0.3.6 13/06/2022 and simple update in the asus center of the HAL and hardware
installing latest corsair ICUE
Install razer synapse3 latest version
install chroma control 0.14

graphics card and memory detected in armory crate (be careful after restarting this hardware update will automatically launch
global armory crate update and high chance you will lose sight of graphics card and memory)
chroma control well installed in synapse -chroma connect
chroma control ram bar synchronized with synapse but not graphics card
Corsair Void headset always in sync too

I will test this evening with a fresh win 11 to put back the full package which detects the graphics card and the ram and test the nvidia driver versions from 512.95
and install each monthly news until the 517.48 to know until when chroma control works
i will let you know tomorrow
have a good day

**Comment by XRedCubeX** [comment] 2023-01-01 12:29
I have the same problem, I have an Nvidia ASUS RTX 2070 Advanced and the GPU LEDs don't color, has a solution been found?

**Comment by AndrewBabbitt97** [comment] 2023-01-13 00:11
We have a solution for this in the upcoming release, will try to get it out soon. Will require running the ASUS module as admin.

**Comment by SCDoll12** [comment] 2023-01-13 04:11
That is awesome! I can’t wait to try it! Thanks!

**Comment by AndrewBabbitt97** [comment] 2023-02-12 01:34
Reports have indicated that this has been fixed in the latest nvidia / Armory Crate updates.

**Closed by AndrewBabbitt97** 2023-02-12 01:34 UTC
Labels: bug

**Comment by Kukulkahn** [comment] 2023-02-15 00:11
That's right! Everything fixed and working as intended with latest Nvidia 528.49 drivers and Armoury Crate VGA HAL  0.0.5.7.

Thank you for your time Andrew!
