### ISSUE TITLE
Doesn't seem to do anything

### ISSUE THREAD

**Issue by Astrikal** [ChromaControl/ChromaControl#3] opened 2020-03-18 10:07 UTC
I installed the program, but it doesn't seem to work. I dont see a Corsair entry in Razer connect.

**Comment by OAlienado** [comment] 2020-03-22 02:45
Same thing with me. Corsair goes into SDK mode, but does not show up in Synapse.

**Comment by cbellmyer** [comment] 2020-03-28 17:17
Duplicate of #2

**Comment by Invicia** [comment] 2020-06-09 17:35
Same for me, Aura goes to standby mode but it won't show any modified modules on my chroma studio. i cant find logs since its not even stored in the files perhaps

**Comment by crscaballero** [comment] 2020-06-25 02:41
Same situation here

**Comment by AndrewBabbitt97** [comment] 2021-01-31 22:02
Closing due to new MSIX beta. Issue should now be resolved.

**Closed by AndrewBabbitt97** 2021-01-31 22:02 UTC
