### ISSUE TITLE
gskill ram does not sync

### ISSUE THREAD

**Issue by andr-lol** [ChromaControl/ChromaControl#43] opened 2021-03-17 11:01 UTC
eight of the RAMs are  sync in armoury crate, but only four are recognized in razer synapse

**Comment by AndrewBabbitt97** [comment] 2021-03-17 14:47
Synapse doesn't recognize individual ram sticks

**Comment by MarshallYTHD** [comment] 2021-03-17 15:10
I thinks he means that only half of them are syncing with chroma control

**Comment by AndrewBabbitt97** [comment] 2021-03-17 16:11
If sticks aren't syncing restart, if it continues upload your log file from %localappdata%\Packages\ChromaControl.Asus_846pf09jn2fpg\LocalCache\Local\ChromaControl\logs

**Comment by andr-lol** [comment] 2021-03-18 10:38
2021-03-18T19:35:13.7631160+09:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Application started. Press Ctrl+C to shut down.
2021-03-18T19:35:13.7707359+09:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Hosting environment: Production
2021-03-18T19:35:13.7707695+09:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Content root path: C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus
2021-03-18T19:35:14.7563407+09:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Initializing Chroma Control - ASUS...
2021-03-18T19:35:15.7690247+09:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Initializing RGBKit...
2021-03-18T19:35:58.6951993+09:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Initializing Razer Chroma Connect API...
2021-03-18T19:35:58.7373272+09:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Found Device: AURA - ENE_RGB_For_ASUS0 - 5 Lights
2021-03-18T19:35:58.7373613+09:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Found Device: AURA - ENE_RGB_For_ASUS1 - 5 Lights
2021-03-18T19:35:58.7373682+09:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Found Device: AURA - ENE_RGB_For_ASUS2 - 5 Lights
2021-03-18T19:35:58.7373741+09:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Found Device: AURA - ENE_RGB_For_ASUS3 - 5 Lights
2021-03-18T19:35:58.7373867+09:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Found Device: AURA - RYUJIN 1 - 5 Lights
2021-03-18T19:35:58.7373918+09:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Found Device: AURA - Mainboard_Master - 7 Lights
2021-03-18T19:35:58.7373992+09:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Found Device: AURA - Mainboard_Slave - 7 Lights
2021-03-18T19:35:58.7374037+09:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Found Device: AURA - AddressableStrip 1 - 120 Lights
2021-03-18T19:35:58.7374078+09:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Found Device: AURA - AddressableStrip 2 - 120 Lights
2021-03-18T19:35:58.7374134+09:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Chroma Control - ASUS started successfully!
2021-03-18T19:36:00.2873500+09:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Razer Chroma Broadcast API connected

**Comment by Hotpepere** [comment] 2021-03-21 09:55
> eight of the RAMs are sync in armoury crate, but only four are recognized in razer synapse

For info G-Skill is compatible with Chroma connect and yes neither armory crate, nor Chroma control allows to separate the lighting from the ram bars separrement. I myself have 4 DDR4 G-Skill trident bars.
The only solution for the moment (while keeping our dear friend Andrew integrating the G-skill bars in separate management of chroma control :)) I advise you to deactivate the management of the ram bars on armory crate and to install the G software -skill lighning which works flawlessly via chroma and allows you to separate each strip.apr against attention the G-skill software consumes a lot of CPU just like Chroma connect (for me it is the case with an Intel processor). install the latest Beta version of their software available in this link.
https://www.gskill.us/forum/forum/product-discussion/ddr4/trident-z-rgb/166500-trident-z-lighting-control-v1-00-24beta-cpu-usage-fix

**Comment by Hotpepere** [comment] 2021-03-21 17:54
Ok I am able to provide a lasting solution for this problem.
1 - Uninstall Armory Crate via the uninstaller armory crate here -> https://www.asus.com/supportonly/Armoury%20Crate/HelpDesk_Download/
2-Uninstall your G-skill software
2- pc restart
3-basic cleaning with utility such as C-Cleaner
4-shut down your PC and physically cut off the power supply (the rgb being often still powered on the asus card off). This is essential to reset the RGB of the ram bars after a few minutes
5- restart and installation of the latest (beta) G-skill 1.0.0.24 available here -> https://www.gskill.us/forum/forum/product-discussion/ddr4/trident-z-rgb/166500-trident- z-lighting-control-v1-00-24beta-cpu-usage-fix
6-set in external link and apply the modifications in the software
7-direction Razer Chroma and test via vizualiser and studio and if everything is ok
8- installation of armory crate
9- uncheck in Asus Aura the support for G-Skill rams

**Comment by AndrewBabbitt97** [comment] 2021-06-11 00:12
In the future I may not support GSkill software at the same time as the AURA Chroma Control module. There may be conflicts with this, but I need to do more testing to verify.

**Comment by AndrewBabbitt97** [comment] 2021-07-05 23:05
Duplicate of #40

**Closed by AndrewBabbitt97** 2021-07-05 23:05 UTC
Labels: bug, documentation
