### ISSUE TITLE
Asus GPU

### ISSUE THREAD

**Issue by r200cjt** [ChromaControl/ChromaControl#239] opened 2023-03-21 23:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Just set up a new rig, iCue native components working flawlessly, Asus is mostly working, motherboard lighting working as expected however Asus GPU lighting either remains off or reverts to default lighting set up in ArmoryCrate - nor is it being found by the chroma control module by the looks of it

![asus chroma control](https://user-images.githubusercontent.com/55891184/226765249-0ac39ec1-dfea-43ae-bb18-3b32a4cdad22.png)

It is detecting the addressable strips capability (which aren't installed)

unsure if it's possible to control all lighting from iCue as it detects all devices? Am currently unable to control any lighting of Asus products through iCue at any point even when not trying to sync.

### Expected behavior

would ideally like the GPU lighting to work in sync with everything else

### Version number

Armoury Crate: 5.4.10.1, Synapse 20230315

### Anything else?

Hardware mentioned:
Asus TUF Gaming Z790-Plus Wifi
Asus TUF Gaming 4070Ti

**Comment by AndrewBabbitt97** [comment] 2023-03-29 22:29
Update GPU drivers to latest version, then report back

**Comment by AndrewBabbitt97** [comment] 2023-03-29 22:30
I'm assuming this is a duplicate of #178

**Comment by AndrewBabbitt97** [comment] 2023-04-12 10:09
Seeing as its likely a duplicate and OP hasn't responded, I'm closing this issue.

Update GPU drivers should resolve the problem.

**Closed by AndrewBabbitt97** 2023-04-12 10:09 UTC
