### ISSUE TITLE
Installation error  0.1.4.0

### ISSUE THREAD

**Issue by erickcu1416** [ChromaControl/ChromaControl#198] opened 2022-12-27 19:13 UTC
Mensaje de error en la instalación de la aplicación: Deployment Add operation with target volume C: on Package ChromaControl_0.1.4.0_neutral_~_s9a324077yex8 from:  (ChromaControl_0.1.4.0_x86_x64.msixbundle)  failed with error 0x80D03805. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x80d03805)

**Comment by Paslik19** [comment] 2022-12-28 14:04
I have the same situation: Failed to install the program. Error message: Deployment Add operation with target volume C: on Package ChromaControl_0.1.4.0_neutral_~_s9a324077yex8 from: (ChromaControl_0.1.4.0_x86_x64.msixbundle) failed with error 0x80D02002. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x80d02002)

**Comment by AndrewBabbitt97** [comment] 2023-01-04 08:53
This is an issue with your windows install, I dont have a solution for it as I cannot reproduce the error. Likely something wrong with storage devices.

**Comment by AndrewBabbitt97** [comment] 2023-01-13 00:16
Will be resolved in the upcoming release, were getting rid of MSIX.

**Closed by AndrewBabbitt97** 2023-01-13 00:16 UTC

**Comment by adamkangas87** [comment] 2023-03-30 12:30
I am having this issue with a fresh build. I've used the latest version from the website. 

Possible related issue.
https://techcommunity.microsoft.com/t5/msix/deployment-add-operation-with-target-volume-c-on-package/m-p/2086076

my c drive is a raid volume if that is of any help.
