### ISSUE TITLE
Asus unreachable

### ISSUE THREAD

**Issue by Infateshands** [ChromaControl/ChromaControl#142] opened 2021-09-14 12:29 UTC
Have installed chroma control from website. Asus is detected in synapse but unreachable

**Comment by AndrewBabbitt97** [comment] 2021-09-14 17:27
Reinstall the connect module in Synapse and check your antivirus it could be blocking the connection

**Comment by gonyoshi** [comment] 2021-09-14 18:06
Hi Andrew! first at all, really thank you for continuing to work on this! second I have the same issue, I used to have the previous version "Aura Connect" and a few days ago it didnt synchronize anymore. I checked the Aura app but figured a different colour (my mobo was blue and the option checked was red) so I opened the ASUS armoury crate and update all. Now apparently is Armoury Crate who control de RGB from MOBO, I have "ASUS Connect" installed in my pc apart from "Chroma Control", toggle in on but still Unreachable. I searched but I couldn't realize, how do I reinstall it the module in Synapse? Should uninstall the ASUS Connect too? Thanks!

**Comment by c4shflo** [comment] 2021-09-14 20:54
I am having the same issue. Asus seems to not respond to sync anymore. It started for me 2 or 3 weeks ago after an Armoury Crate update. I wish I could tell you the exact version but sadly I did not make a note of it. Other updates to components have come through in Armoury Crate since although I do not think Armoury Crate itself has been updated again.

**Comment by AndrewBabbitt97** [comment] 2021-09-16 21:37
Sounds like an Armory Crate issue. Not much I can really suggest beyond reinstalling things.

**Comment by gonyoshi** [comment] 2021-09-16 23:52
Well not work for me, I re installed everything again in several different order. I think the issue is related to the change of apps controlling RGB in ASUS. "Aura" is not longer available, instead you have to use "Armoury Crate" who controls RGB and a new app "Aura Creator" if it is installed now this second app controls RGB, I think this changes bring trouble to your app. I try several times uninstalling, reinstalling and rebooting everytime unsuccessfully, toggle do nothing. Now I have not anymore the "Asus" module in device and disappear from "Studio" and "Connect" tab, in Synapse. I also tried reinstall "Aura Connect" but it didn't work either. 
I ran out of options 😞

**Comment by gonyoshi** [comment] 2021-09-17 00:18
Leave you here the debug log, maybe can help you to find a solution

info: ChromaControl.Hosting.ModuleService[0]
      Initializing Chroma Control - Asus v0.1.3...
info: ChromaControl.Hosting.ModuleService[0]
      Initializing Device Provider...
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: Mainboard_Master - 4 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Found Device: AddressableStrip 1 - 120 Lights
info: ChromaControl.Hosting.ModuleService[0]
      Initializing Razer Chroma Broadcast SDK...

Always freezes in that line

**Comment by AndrewBabbitt97** [comment] 2021-09-17 00:23
Reinstall the chroma connect module in Synapse. This is an issue with Synapse not Chroma Control.

**Comment by gonyoshi** [comment] 2021-09-17 01:08
OMG it works! REALLY THANKS man for all the support, dont get it the first time and I didnt find it in Synapse. Just went to Dashboard tab, look for "Chroma Connect" and click the X , Synapse reboot, then go to Modules tab and click Add in "Chroma Connect", Synapse reboot again, toggle on, reboot Synapse manually and "Chrome Connect" detect "Chroma Control Asus" in Connect > Devices tab also Asus appear in Studio tab. Sorry for not understanding you correctly first and for my shitty english too xd

**Comment by thethiny** [comment] 2021-09-27 10:02
Issue fixed with recent Armoury Crate update. Go to Armoury Crate, enable sync, do the calibrate (when you calibrate it resets). Then turn on "Sync with Game" on the bottom of Armoury Crate Sync Tab, then restart your PC and DO NOT OPEN ARMOURY CRATE. Only Open Rzer.

**Comment by breshiah** [comment] 2021-10-11 20:31
Thanks for this thread. It helped to solve the issues that I was having, for the most part. Temporarily disabling Norton allowed Chroma Control to connect to Synapse. However, with the new Armory Crate update, it does seem that Aura Sync (and Aura Creator) will take over Asus devices when that tab is accessed via Armory Crate. As @thethiny recommended, my solution has been to avoid clicking on that tab in Armory Crate. i.e., opening Armory Crate seems to keep Synapse in control; Aura Sync only takes over when the Aura Sync tab is selected.

I recently switched over to Chroma Control from AuraConnect. Before this change, when the Armory Crate Aura Sync tab was selected a window would pop up on Armory Crate effectively stating and providing an indication that the RGB for these devices is being controlled by AuraConnect (and Synapse). I hope Armory Crate implements something similar to this in a future update. Not a huge deal to avoid clicking the Aura Sync tab but it would be nice to have that recognition and safeguard feature implemented to avoid accidental clicks and provide some integration robustness.

If anyone reading this is using Chroma Control and can access the Aura Sync tab without it taking over, please let me know. Perhaps I would need to try re-installing Armory Crate?

and thanks @AndrewBabbitt97 for the awesome app.

**Closed** 2023-01-13 00:01 UTC
