### ISSUE TITLE
how to set this up

### ISSUE THREAD

**Issue by alright-sudo** [ChromaControl/ChromaControl#123] opened 2021-07-28 16:37 UTC
so maybe i do not understand how this work's but when i downloaded the program and went to try and set it up. it does not give me any exe files to do so. i am sort of lost what to do after i have downloaded and extracted this file

**Comment by AndrewBabbitt97** [comment] 2021-07-28 16:57
Duplicate of #33 #55 #72 #91

Please make sure you search existing issues before opening new ones.

**Closed** 2021-07-28 16:58 UTC
