### ISSUE TITLE
Ensure Chroma Control Works With Sleep

### ISSUE THREAD

**Issue by Funkybrunk** [ChromaControl/ChromaControl#37] opened 2021-03-12 21:26 UTC
Wonderful work on this, I've followed over from the Aura Connect project, and everything is syncing up nicely.

Unfortunately, like Aura Connect, Chroma Control is preventing my machine from sleeping.
I know this isn't a high priority for everyone, most keep their machines on 24/7

My unscientific approach to arrive at this conclusion was:
Install Chroma Control, set CPU timeout to 1min. Wait. CPU doesn't sleep
Uninstall Chroma Control. Wait. CPU sleeps.
Reinstall Chroma Control. Wait. CPU doesn't sleep.
Uninstall Chroma Control. Wait. CPU sleeps.
Reinstall Chroma Control. Wait. CPU doesn't sleep.
..and so on.

For Aura Connect, you mentioned that in order to resolve the issue, you would need to rewrite in a different language. I hope that isn't the case here.

I will continue to use your great work regardless. Thank you for developing this.

**Comment by AndrewBabbitt97** [comment] 2021-03-12 23:02
Auto sleep may be fixable, I'm gonna have to look into some Windows APIs to find anything.
Manually sleeping should work for the time being, in general I'm not entirely sure what specifically is causing it to prevent the PC from sleeping. Some manual intervention may be required using Windows APIs to get this to work, and how this will interact with the various device SDKs will be another thing to evaluate.

Will be able to look into this next month after I am finished moving.

**Comment by Tomerkat** [comment] 2021-04-13 06:29
Fixed it. I changed the "Hardware Lightning" in iCue to no color.

**Comment by stubbz00** [comment] 2021-06-08 16:32
I came across this post looking for a solution to this as well.  I'm hoping that this can be resolved.

Thank you,

**Comment by AndrewBabbitt97** [comment] 2021-07-02 09:37
So I did a lot more playing around (annoyingly waiting for my PC to sleep that is) and have retested this for the first time in a long time.

Bear in mind I'm on Windows 11 now for these tests.

I am no longer able to replicate this issue with the ASUS module. I have validated that Chroma Control is connected to both the ASUS SDK as well as Synapse and fully functioning. With Chroma Control running and the display timeout set to 1 minute and the sleep timeout set to 2 minutes (I could not get my PC to sleep at all without setting the display timeout to be shorter than the sleep timeout regardless of if Chroma Control was installed or not). With this my PC sleeps every time as expected. I am not able to reproduce a situation where Chroma Control specifically is the cause of my PC not being able to sleep.

Keep in mind that this testing was done on Windows 11 with the latest version of Armory Crate and Razer Synapse. Your milage may vary. This is however showing me that the issue isn't inside Chroma Control. If the issue is in the Corsair module then it may be an issue with the way Corsairs SDK works. This is totally a possibility. I don't personally use the Corsair module anymore so anything's possible.

**Comment by stubbz00** [comment] 2021-07-02 17:10
Hey @AndrewBabbitt97

I appreciate you taking the time to look at this again.  I don't have any corsair products anymore so that shouldn't be the issue for me either.  I just saw an update for Armoury Crate so I will reinstall Chroma Control and see if it was fixed with the Armoury Crate update.

**Comment by norimicry** [comment] 2023-10-14 14:34
+1 Does not resume control after sleep using Armory Crate + Synapse. No Corsair is being used.

**Comment by PavolCurilla** [comment] 2024-07-18 06:09
Unfortunately this is still not working properly. Armory Crate + Synapse.

**Comment by AndrewBabbitt97** [comment] 2024-07-18 20:01
Fixed in upcoming release.

**Closed** 2024-07-29 09:58 UTC
Labels: bug

**Comment by Ninowis** [comment] 2025-11-05 22:48
Hey @AndrewBabbitt97
Thanks for your work on this awesome plugin :)

Are you still working on this project at all?
If so is there still an upcoming release for those fixes?

**Comment by andrewbabbittdev** [comment] 2025-11-06 04:55
@Ninowis This is fixed in our dev1 release, we wont have a stable release of that until some OpenRGB APIs get fleshed out more as its what we are using for all future versions of Chroma Control. dev1 is a rework of the entire project to move away from ICue and Armory Crate / Aura. dev1 is available in our discord server development channel.

I use the dev build daily on my machine, there are bugs and missing things there that we are waiting on stuff from OpenRGB to implement. Once those are in we will move forward with more builds.
