### ISSUE TITLE
Corsair Products Don't Lightup after Awaking PC from Sleep

### ISSUE THREAD

**Issue by BB4LIFE** [ChromaControl/ChromaControl#177] opened 2022-06-18 09:57 UTC
After awaking my PC from sleep, my corsair ram and fans stop lighting up.  They all sync fine after a restart though.

**Comment by Kaldaka** [comment] 2022-09-11 23:00
Am having the same problem. I posted as well with a bit more information. Maybe the way I described the problem is also the same for you?

**Comment by AndrewBabbitt97** [comment] 2023-01-13 00:10
Duplicate of #37

**Closed by AndrewBabbitt97** 2023-01-13 00:10 UTC
