### ISSUE TITLE
Chroma control for Asus doesn't work after wake up

### ISSUE THREAD

**Issue by hugopua** [ChromaControl/ChromaControl#103] opened 2021-06-21 08:20 UTC
Hi,

As title mentioned, the Chroma connect for Asus doesn't work after wake up. Please note. Thank you.

**Comment by AndrewBabbitt97** [comment] 2021-06-21 14:33
Need logs and timestamps at which the error occurs, there may not be anything I can do to fix this one.

**Comment by hugopua** [comment] 2021-06-22 07:31
2021-06-22T15:25:46.5361849+08:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Application started. Press Ctrl+C to shut down.
2021-06-22T15:25:46.5388333+08:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Hosting environment: Production
2021-06-22T15:25:46.5388591+08:00	INFO	[Microsoft.Hosting.Lifetime]	[0]	Content root path: C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus
2021-06-22T15:25:47.5494203+08:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Initializing Chroma Control - ASUS...
2021-06-22T15:25:48.5725727+08:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Initializing RGBKit...
2021-06-22T15:26:32.6066785+08:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Initializing Razer Chroma Connect API...
2021-06-22T15:26:32.6162452+08:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Found Device: AURA - Corsair Vengeance RGB Pro - 48 Lights
2021-06-22T15:26:32.6162640+08:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Found Device: AURA - Vga 1 - 22 Lights
2021-06-22T15:26:32.6162682+08:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Found Device: AURA - Mainboard_Master - 8 Lights
2021-06-22T15:26:32.6162719+08:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Found Device: AURA - AddressableStrip 1 - 120 Lights
2021-06-22T15:26:32.6162784+08:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Found Device: AURA - AddressableStrip 2 - 120 Lights
2021-06-22T15:26:32.6162817+08:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Chroma Control - ASUS started successfully!
2021-06-22T15:26:32.8254846+08:00	INFO	[ChromaControl.Shared.Worker]	[Logging]	Razer Chroma Broadcast API connected

**Comment by AndrewBabbitt97** [comment] 2021-06-23 20:34
This is a duplicate of #101 same issue technically.

**Closed by AndrewBabbitt97** 2021-06-23 20:34 UTC
